version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elastic-container
    ports:
      - 9200:9200
      - 9300:9300

    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      discovery.type: single-node
      cluster.name: elastic-cluster
      xpack.security.enabled: 'false'

    networks:
      - ek-net

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.2.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200

    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  ek-net:
    driver: bridge
